version: '2.1'

services:
  couchbase: # Couchbase App
    container_name: couchbase
    image: couchbase
    ports:
      - "8091-8094:8091-8094" # Expose port
    volumes: # Attach local data directory
      - "~/Desktop/AdPushup/new-backups:/opt/couchbase/var"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091"]
      interval: 1m30s
      timeout: 10s
      retries: 5
  api: # Node.js App
    container_name: node-api
    build: .
    ports:
      - "8080:8080" # Expose API port
    volumes: # Attach local directory
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/portedApps/node_modules
    depends_on:
      couchbase:
        condition: service_healthy
    command: bash script.sh
    environment: # Set ENV vars
      - Couchbase_URL=couchbase