const AMP_NAV_ITEMS_INDEXES = {
	CREATE_ADS: 'create-ads',
	MANAGE_ADS: 'manage-ads'
};

const AMP_NAV_ITEMS_VALUES = {
	CREATE_ADS: 'Create Ads',
	MANAGE_ADS: 'Manage Ads'
};

const AMP_NAV_ITEMS = {
	[AMP_NAV_ITEMS_INDEXES.CREATE_ADS]: {
		NAME: [AMP_NAV_ITEMS_VALUES.CREATE_ADS],
		INDEX: 1
	},
	[AMP_NAV_ITEMS_INDEXES.MANAGE_ADS]: {
		NAME: [AMP_NAV_ITEMS_VALUES.MANAGE_ADS],
		INDEX: 2
	}
};

export { AMP_NAV_ITEMS_INDEXES, AMP_NAV_ITEMS_VALUES, AMP_NAV_ITEMS };
