const PAYMENT_NAV_ITEMS_INDEXES = {
	DETAILS: 'details',
	HISTORY: 'history',
	BALANCE: 'Balance'
};

const PAYMENT_NAV_ITEMS_VALUES = {
	DETAILS: 'Details',
	HISTORY: 'History',
	BALANCE: 'Balance'
};

const MG_TYPES = {
	PAGE_RPM: 'Page RPM',
	ECPM: 'eCPM',
	REVENUE: 'Revenue'
};

const MG_START_YEAR = 2022;

const PAYMENT_NAV_ITEMS = {
	[PAYMENT_NAV_ITEMS_INDEXES.DETAILS]: {
		NAME: [PAYMENT_NAV_ITEMS_VALUES.DETAILS],
		INDEX: 1
	},
	[PAYMENT_NAV_ITEMS_INDEXES.HISTORY]: {
		NAME: [PAYMENT_NAV_ITEMS_VALUES.HISTORY],
		INDEX: 2
	},
	[PAYMENT_NAV_ITEMS_INDEXES.BALANCE]: {
		NAME: [PAYMENT_NAV_ITEMS_VALUES.BALANCE],
		INDEX: 3
	}
};

export {
	PAYMENT_NAV_ITEMS,
	PAYMENT_NAV_ITEMS_INDEXES,
	PAYMENT_NAV_ITEMS_VALUES,
	MG_TYPES,
	MG_START_YEAR
};
