const ADSTXT_NAV_ITEMS_INDEXES = {
	AUTHENTICATOR: 'authenticator',
	ENTRIES: 'entries'
};

const ADSTXT_NAV_ITEMS_VALUES = {
	AUTHENTICATOR: 'Authenticator',
	ENTRIES: 'Entries'
};

const ADSTXT_NAV_ITEMS = {
	[ADSTXT_NAV_ITEMS_INDEXES.AUTHENTICATOR]: {
		NAME: [ADSTXT_NAV_ITEMS_VALUES.AUTHENTICATOR],
		INDEX: 1
	},
	[ADSTXT_NAV_ITEMS_INDEXES.ENTRIES]: {
		NAME: [ADSTXT_NAV_ITEMS_VALUES.ENTRIES],
		INDEX: 2
	}
};

export { ADSTXT_NAV_ITEMS, ADSTXT_NAV_ITEMS_INDEXES, ADSTXT_NAV_ITEMS_VALUES };
