const PREFIX = `AMP_NEW`;
const AD_ACTIONS = {
	CREATE_AD: `${PREFIX}_CREATE_AD`,
	UPDATE_ADS_LIST: `${PREFIX}_UPDATE_ADS_LIST`,
	REPLACE_ADS_LIST: `${PREFIX}_REPLACE_ADS_LIST`,
	DELETE_AD: `${PREFIX}_DELETE_AD`,
	UPDATE_AD: `${PREFIX}_UPDATE_AD`
};
const GLOBAL_ACTIONS_AMP = {
	SET_CURRENT_AD: `${PREFIX}_SET_CURRENT_AD`
};

export { AD_ACTIONS, GLOBAL_ACTIONS_AMP };
