const GLOBAL_ACTIONS = {
	FETCH_GLOBAL_DATA: 'FETCH_GLOBAL_DATA',
	REPLACE_NETWORK_TREE: 'REPLACE_NETWORK_TREE'
};
const USER_ACTIONS = {
	LOGOUT_USER: 'LOGOUT_USER',
	REPLACE_USER_DATA: 'REPLACE_USER_DATA',
	UPDATE_AD_NETWORK_SETTINGS: 'UPDATE_AD_NETWORK_SETTINGS'
};
const NETWORK_CONFIG_ACTIONS = {
	REPLACE_NETWORK_CONFIG: 'REPLACE_NETWORK_CONFIG'
};
const REPORTS_ACTIONS = {
	REPLACE_REPORTS_DATA: 'REPLACE_REPORTS_DATA'
};
const SITE_ACTIONS = {
	REPLACE_SITE_DATA: 'REPLACE_SITE_DATA',
	UPDATE_SITE_DATA: 'UPDATE_SITE_DATA',
	UPDATE_SITE_STEP: 'UPDATE_SITE_STEP',
	UPDATE_SITE_APCONFIG: 'UPDATE_SITE_APCONFIG'
};
const UI_ACTIONS = {
	HIDE_NOTIFICATION: 'HIDE_NOTIFICATION',
	SHOW_NOTIFICATION: 'SHOW_NOTIFICATION'
};

export {
	GLOBAL_ACTIONS,
	USER_ACTIONS,
	NETWORK_CONFIG_ACTIONS,
	SITE_ACTIONS,
	UI_ACTIONS,
	REPORTS_ACTIONS
};
