const CHECK_INVENTORY = 'CHECK_INVENTORY';
const FETCH_ALL_BIDDERS = 'FETCH_ALL_BIDDERS';
const GET_SETUP_STATUS = 'GET_SETUP_STATUS';
const ADD_BIDDER = 'ADD_BIDDER';
const UPDATE_BIDDER = 'UPDATE_BIDDER';
const FETCH_INVENTORIES = 'FETCH_INVENTORIES';

export {
	CHECK_INVENTORY,
	FETCH_ALL_BIDDERS,
	GET_SETUP_STATUS,
	ADD_BIDDER,
	UPDATE_BIDDER,
	FETCH_INVENTORIES
};
