const CHECK_INVENTORY = 'CHECK_INVENTORY';
const FETCH_ALL_BIDDERS = 'FETCH_ALL_BIDDERS';
const ADD_BIDDER = 'ADD_BIDDER';
const UPDATE_BIDDER = 'UPDATE_BIDDER';
const DELETE_BIDDER = 'DELETE_BIDDER';
const FETCH_INVENTORIES = 'FETCH_INVENTORIES';
const UPDATE_INVENTORIES_HB_STATUS = 'UPDATE_INVENTORIES_HB_STATUS';
const SET_DFP_SETUP_STATUS = 'SET_DFP_SETUP_STATUS';
const UPDATE_ADSERVER_SETUP_STATUS = 'UPDATE_ADSERVER_SETUP_STATUS';
const GET_HB_INIT_DATA = 'GET_HB_INIT_DATA';
const SET_UNSAVED_CHANGES = 'SET_UNSAVED_CHANGES';
const FETCH_HB_RULES = 'FETCH_HB_RULES';
const UPDATE_HB_RULES = 'UPDATE_HB_RULES';

export {
	CHECK_INVENTORY,
	FETCH_ALL_BIDDERS,
	ADD_BIDDER,
	UPDATE_BIDDER,
	DELETE_BIDDER,
	FETCH_INVENTORIES,
	UPDATE_INVENTORIES_HB_STATUS,
	SET_DFP_SETUP_STATUS,
	UPDATE_ADSERVER_SETUP_STATUS,
	GET_HB_INIT_DATA,
	SET_UNSAVED_CHANGES,
	FETCH_HB_RULES,
	UPDATE_HB_RULES
};
