const PREFIX = `INNOVATIVE_ADS`;
const AD_ACTIONS = {
	CREATE_AD: `${PREFIX}_CREATE_AD`,
	UPDATE_ADS_LIST: `${PREFIX}_UPDATE_ADS_LIST`,
	REPLACE_ADS_LIST: `${PREFIX}_REPLACE_ADS_LIST`,
	DELETE_AD: `${PREFIX}_DELETE_AD`,
	UPDATE_AD: `${PREFIX}_UPDATE_AD`
};
const UI_ACTIONS = {
	SET_CREATE_AD_ERROR: `${PREFIX}_SET_CREATE_AD_ERROR`,
	SET_CREATE_AD_LOADER: `${PREFIX}_SET_CREATE_AD_LOADER`,
	SET_FETCH_ADS_ERROR: `${PREFIX}_SET_FETCH_ADS_ERROR`
};
const GLOBAL_ACTIONS = {
	SET_CURRENT_AD: `${PREFIX}_SET_CURRENT_AD`,
	SET_META: `${PREFIX}_SET_META`,
	UPDATE_META: `${PREFIX}_UPDATE_META`,
	UPDATE_AD_TRACKING_LOGS: `${PREFIX}_UPDATE_AD_TRACKING_LOGS`,
	SET_AD_TRACKING_LOGS: `${PREFIX}_SET_AD_TRACKING_LOGS`
};
const API_PATHS = {
	FETCH_ADS: '/innovativeAdsManager/data/fetchAds',
	CREATE_AD: '/innovativeAdsManager/data/createAd',
	DELETE_AD: '/innovativeAdsManager/data/deleteAd',
	MODIFY_AD: '/innovativeAdsManager/data/modifyAd',
	MASTER_SAVE: '/innovativeAdsManager/data/masterSave'
};

export { AD_ACTIONS, UI_ACTIONS, GLOBAL_ACTIONS, API_PATHS };
