const PAGEGROUP_ACTIONS = {
	CREATE_PAGEGROUPS: 'CREATE_PAGEGROUPS',
	UPDATE_PAGEGROUP: 'UPDATE_PAGEGROUP'
};
const ACCOUNT_ACTIONS = {};

const FETCH_HB_RULES = 'FETCH_HB_RULES';
const UPDATE_HB_RULES = 'UPDATE_HB_RULES';

const FC_SETTINGS = {
	LABEL_COLOR: 'rgb(251, 248, 248)',
	LABEL_BG_COLOR: 'rgb(106, 90, 90)'
};
export { PAGEGROUP_ACTIONS, ACCOUNT_ACTIONS, FETCH_HB_RULES, UPDATE_HB_RULES, FC_SETTINGS };
