const UPDATE_PNP_CONFIG = 'UPDATE_PNP_CONFIG';
const REPLACE_PNP_CONFIG = 'REPLACE_PNP_CONFIG';
const UPDATE_PNP_CONFIG_KEY = 'UPDATE_PNP_CONFIG_KEY';

export { UPDATE_PNP_CONFIG, REPLACE_PNP_CONFIG, UPDATE_PNP_CONFIG_KEY };
